[package]
name = "game-of-life"
version = "0.1.0"
authors = ["Pavel Hrách <pavel@hrach.email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.1"
raqote = "0.8.0"
ndarray = "0.13.1"
rand = "0.7.3"